### ISSUE TITLE
NENG 612 Final Project

### ISSUE THREAD

**Issue by Ahoy86er** [Ahoy86er/NENG-612#1]
Capt. Bevins,
I have posted my final paper, my calibration python code and the spreadsheets for calibrations and foils which I showed some of my work on if you would like to look those over.

Thank you,
Amy

**Comment by jamesbevins** [comment]
Good job!  

I have posted edits and feedback.  To be honest, I did not have time to go through your code and analysis, but I would like to sit down and do that.  Down the road, maybe after the experiment in October before you start analyzing data.
